addons: 
  postgresql: "11"
cache: npm
deploy: 
  github_token: $GITHUB_TOKEN
  keep_history: true
  provider: pages
  skip_cleanup: true
  true: 
    branch: develop
install: 
  - "npm ci"
language: node_js
node_js: 
  - node
notifications: 
  email: false
script: 
  - "nodemon server.js"
  - "npm run test"
services: 
  - postgresql