cache: npm
deploy: 
  github_token: $GITHUB_TOKEN
  keep_history: true
  provider: pages
  skip_cleanup: true
  true: 
    branch: develop
env: 
  global: 
    - "NODE_TLS_REJECT_UNAUTHORIZED = 0"
install: 
  - "npm ci"
language: node_js
node_js: 
  - node
notifications: 
  email: false
script: 
  - "npm run test"
