cache: npm
deploy: 
  github-token: $GITHUB_TOKEN
  provider: pages
  skip-cleanup: true
  true: 
    branch: develop
install: 
  - "npm ci"
language: node_js
node_js: 
  - node
script: 
  - "npm test"
  - "npm run build"