cache: npm
deploy: 
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on: 
    branch: develop
install: 
  - "npm ci"
language: node_js
node_js: 
  - "node"
notifications: 
  email: false
script: 
  - "npm run test"