cache: npm
default: 
  cv1: "<%=ENV[NODE_TLS_REJECT_UNAUTHORIZED=0] %>"
deploy: 
  github-token: $GITHUB_TOKEN
  provider: pages
  skip-cleanup: true
  true: 
    branch: develop
install: 
  - "npm ci"
language: node_js
node_js: 
  - "10"
notifications: 
  email: false
script: 
  - "npm run test"